### ISSUE TITLE
Hover is not working

### ISSUE THREAD

**Issue by dcangulo** [miblanchard/react-native-slider#100]
I am using [react-native-web-hooks](https://github.com/evanbacon/react-native-web-hooks) to add hover effects for web. But it doesn't seem to work inside on `renderThumbComponent`.

Reproduce: https://snack.expo.io/@dcangulo/hover-not-working

As you can see when I render `<CustomThumb />` outside the `renderThumbComponent`, it works as expected. But if I put it inside `renderThumbComponent`, the hover effect stops working.

Using css `:hover` also does not work.

See: https://snack.expo.io/@dcangulo/hover-not-working-2

**Comment by dcangulo** [comment]
It seems like `styles.touchArea` is covering the entire slider that's why hover doesn't seem to work.

**Comment by webraptor** [comment]
```
import {
    Animated,
    Image,
    PanResponder,
    View,
    Easing,
    I18nManager,
} from 'react-native';
```
The package uses react-**native** code ...
