### ISSUE TITLE
renderAboveThumbComponent index is not updating

### ISSUE THREAD

**Issue by ayusch-apps-curefit** [miblanchard/react-native-slider#149]
Hi there,

I'm using the slider as such 

```
      
    <SliderContainer sliderValue={value} trackMarks={trackMarks}>
<Slider
        minimumValue={minimumValue}
        maximumValue={maximumValue}
        step={step}
        renderAboveThumbComponent={(index) => {
          console.log('Here 1: ' + index);
          if (!renderAboveThumbComponent || !renderAboveThumbComponent(index))
            return undefined;
          const iconName = renderAboveThumbComponent(index);

          return (
            <Box left={-16}>
              {/*@ts-ignore*/}
              <Icon name={iconName} fontSize={50} />
            </Box>
          );
        }}
      />
</SliderContainer>
```

But the index does not update when I move the slider thumb. 
Log always prints

`Here 1: 0`

**Comment by miblanchard** [comment]
@ayusch-apps-curefit - The index value is not the current slider value it is the index of the particular thumb from the values array.  If you need access to the `value` that can be added as it is in scope from the map function on line 639 in Slider.js.  

Hope that helps.  I'm going to close this issue, but I'd welcome a PR if you wanted to add value as a 2nd parameter to the renderAboveThumbComponent function.
