### ISSUE TITLE
Getting "Invariant Violation: inputRange must be monotonically non-decreasing" error

### ISSUE THREAD

**Issue by kckunal2612** [miblanchard/react-native-slider#271]
First of all, I'd like to thank you for providing this library - it has been extremely useful for my projects.
I've recently been seeing an error when trying to open a component using the Slider -
`Invariant Violation: inputRange must be monotonically non-decreasing`
This crashes the app on first use, but works on the subsequent launches.

Here's my environment info - 
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 856.17 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by miblanchard** [comment]
@kckunal2612 - Glad you are enjoying it!  Can you provide a minimal sample that I can look at to reproduce this crash?  I'm using it with the same version of react-native and have never come across that error.

**Comment by kckunal2612** [comment]
@miblanchard never mind, it was an issue with the values I was passing to the Slider - some of them were less than zero when they shouldn't have been. You can close this issue, thanks for following up!
