### ISSUE TITLE
Bug: Does not work vertically

### ISSUE THREAD

**Issue by TimP4w** [miblanchard/react-native-slider#294]
I need a vertical slider, but when I set the `containerStyle` prop with:

```
{
    transform: [{rotate: '-90deg'}],
}
```
The slider is displayed correctly but it does not react as expected to touch events. I can tap on the track and the thumb moves more or less to the correct position, but it doesn't otherwise follow the movement of the finger. 

The debugTouchArea seems to be correct tho.
![image](https://user-images.githubusercontent.com/17258527/122935344-8d93be80-d370-11eb-8606-1a285189b4ab.png) ![image](https://user-images.githubusercontent.com/17258527/122934671-06dee180-d370-11eb-9363-53ba503675d1.png)

https://user-images.githubusercontent.com/17258527/122935724-dcd9ef00-d370-11eb-8025-c2986e25799b.mov

**Comment by miblanchard** [comment]
@TimP4w This isn't a use case I've come across in our use of this library. I'd welcome a PR to add/polish this behavior though!

**Comment by Sharcoux** [comment]
Using a rotation is probably not a good way to handle this case because the slider uses the size of the container to deduce it's value, and after a rotation, width becomes height and height becomes width, probably making the calculations all wrong

**Comment by Sharcoux** [comment]
While waiting for a fix here, you can try using [@Sharcoux /slider](https://www.npmjs.com/package/@sharcoux/slider) if you need a solution for this use case.

**Comment by miblanchard** [comment]
@TimP4w - I may consider including this capability when I work on a new release (hopefully soon). I'm intending to convert to TS and use reanimated 2 and gesture handler.  If I can accommodate rotation in that I will add a mechanism. No promises though, since it is still not a use case I really need.

**Comment by miblanchard** [comment]
Feature added by #323.

Closing this issue as resolved. Thank you @geert-untire !
