### ISSUE TITLE
Get "attempting to disconnect view that has not been connected with the given animated node" Error

### ISSUE THREAD

**Issue by aminsaedi** [miblanchard/react-native-slider#298]
Hi.
i got this error when i change the value of slider
`attempting to disconnect view that has not been connected with the given animated node`

**Comment by miblanchard** [comment]
@aminsaedi Can you provide any more information or a reproducible example of how you are using the library?

**Comment by miblanchard** [comment]
@aminsaedi I'm gonna close this since you haven't provided a reproducible example and I can't reproduce on my own.
