### ISSUE TITLE
TrackClickable on slider with tracks value round problem

### ISSUE THREAD

**Issue by niputy** [miblanchard/react-native-slider#310]
When you enable trackClickable on slider with tracks slider rounds the value towards the left. Can you add some customization for that or just normal round?

**Comment by miblanchard** [comment]
@niputy this hasn't come up as a problem yet for us, so do you think Math.round would be better, or an option to choose the rounding type?

**Comment by niputy** [comment]
Actually, additional customization is not necessary. I think Math.round will be enough.

**Comment by miblanchard** [comment]
@niputy can you point to where you believe the values are being rounded down?  I did a quick search the other day and all rounding operations are using Math.round, and not Math.floor or Math.ceil

**Comment by niputy** [comment]
Unfortunately, Idk how to test it properly but bug definitely exist. I think smth wrong with one of the Math.min

**Comment by miblanchard** [comment]
@niputy please provide an example snack or something to reproduce what you consider a bug.  We user this in several apps and have not identified this problem.

**Comment by niputy** [comment]
Simplest example:
`<Slider
  value={3}
  minimumValue={1}
  maximumValue={5}
  step={1}
  trackMarks={[1, 2, 3, 4, 5]}
  trackClickable={true}
/>`

**Comment by miblanchard** [comment]
@niputy and specifically you are saying that clicking somewhere on the track where the value is greater than .5 (so 1.6 or 3.7 in this example) is resulting in the value being rounded down vs. rounding up to the nearest whole number as you expect?

**Comment by niputy** [comment]
Yep, even value like 1.8 and 1.9 rounded down.

**Comment by miblanchard** [comment]
@niputy - I have a 2.0 branch that I'm working on now, and when I test with the example you shared above it behaves as desired.  .5 and above rounds up, and the rest round down.  In the interim, if you remove the step prop, the thumb will stop exactly where you click the track, but I don't think that is what you want.

**Comment by niputy** [comment]
@miblanchard Nice, let me know when branch 2.0 is live. I will chek it out and close issue. Or how it usually going? I just got a job 3 months ago and first time reported a bug.

**Comment by miblanchard** [comment]
@niputy 2.0 has been published - Testing with the top item in this snack looks to behave like you described.  https://snack.expo.dev/@miblanchard/@miblanchard-react-native-slider

**Comment by niputy** [comment]
That's exactly what I need, thanks!
