### ISSUE TITLE
onValueChange not fired after upgrading to 2.0.1

### ISSUE THREAD

**Issue by pehagg** [miblanchard/react-native-slider#319]
`onValueChange` isn't fired as it used to after upgrading from 1.4.0 to 2.0.1. It's not fired at all. `onSlidingComplete` _does_ fire as before.

**Comment by miblanchard** [comment]
@pehagg 2.0.2 is available now with a fix.

**Comment by pehagg** [comment]
Can verify that the fix works. Thanks!
