### ISSUE TITLE
Add custom components to track

### ISSUE THREAD

**Issue by WenLonG12345** [miblanchard/react-native-slider#324]
Hi, thanks for this awesome fork! 
However, I was wondering how can I add a <Text> or any other component in track, and this component will be overlap when the slider pass through. 

![image](https://user-images.githubusercontent.com/39330565/147343076-3cebaa12-3b18-4179-82d5-49124681c8fd.png)

Something similar to this.
https://github.com/Roxyhuang/react-slide-captcha
![image](https://user-images.githubusercontent.com/39330565/147343316-19f1de82-6298-4a6b-87f4-b7e303741be7.png)

Currently I am using `renderTrackMarkComponent` but I don't think it is a correct way to use it. 
Any suggestion?

**Comment by miblanchard** [comment]
@WenLonG12345 you should be able to place any react component at any position along the track with the function you listed `renderTrackMarkComponent`.  You need to also provide the `trackMarks` prop to indicate where on the track that the component(s) should render. 

Hope this helps.

**Comment by WenLonG12345** [comment]
Hi @miblanchard , `renderTrackMarkComponent` will only add the view to the track, but when the slider pass through, it does not overlap this view. Any idea how to overlap this view?

**Comment by miblanchard** [comment]
@WenLonG12345 do you mean you want the thumb to be above/over the trackMarkComponent? That is the behavior I see currently.

**Comment by miblanchard** [comment]
@WenLonG12345 closing due to lack of response.
