### ISSUE TITLE
How would you make a cache bar?

### ISSUE THREAD

**Issue by igorcesarcode** [miblanchard/react-native-slider#327]
I'm using the library as a slide of a custom video component, but I need to implement cache loading, something like:
![image](https://user-images.githubusercontent.com/44711552/148848947-2f15b8e4-2827-4ea2-a8be-315fb80f048d.png)

cacheValue={playableDuration}
cacheTrackTintColor={'#fffff'}

PS: Sorry my english I'm not native.

**Comment by miblanchard** [comment]
Hey @igorcesarcode - That is a great feature idea.  We also use this for a video slider, but we don't need to show the loading percentage.  

I am happy to review a PR to add just a feature though. 😄

**Comment by igorcesarcode** [comment]
@miblanchard 
I'm glad the idea is useful, I'm currently studying react native and your library was the one that best suited me for building my video component.
I even tried to implement the jugestion, but I'm still a beginner.

Ps: Thank you so much for the wonderful library.

**Comment by miblanchard** [comment]
Closing as not actionable.  This could be a cool feature if anyone is interested in making a PR.
