### ISSUE TITLE
How to integrate with react-native-web?

### ISSUE THREAD

**Issue by fitranto** [miblanchard/react-native-slider#328]
Hi @miblanchard 

i'm using react-native 0.63 and react-native-web 0.13 and run this command
```
expo start:web
```
got this error, any suggestion will help

![image](https://user-images.githubusercontent.com/10884331/149327774-1b78914f-7e42-424f-b181-49f224c711d2.png)

thanks in advance

**Comment by miblanchard** [comment]
Hey @fitranto that appears to be a complication error resulting from my use of optional chaining. You should look into the expo web webpack config to see if it supports that.  My sample expo snack runs fine on web, so they may have updated it to work in a more recent version.

**Comment by fitranto** [comment]
i just run `expo customize:web` which generate `webpack.config.js` and look like this
```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Customize the config before returning it.
  return config;
};
```
how do i make it to work?
i don't really know about this webpack thing

**Comment by miblanchard** [comment]
@fitranto the first step I'd recommend is upgrading your expo, react-native-web, and react-native dependencies in the project.   Within Expo snack there isn't any webpack customization and the library works as intended.

What version of this package are you using, please try the latest of that as well.

**Comment by miblanchard** [comment]
@fitranto  example snack I referenced.

**Comment by fitranto** [comment]
I managed to make it work with app.json settings like this
```
{
  "expo": {
    ...
    "web": {
      "build": {
        "babel": {
          "include": ["@miblanchard/react-native-slider"]
        }
      }
    }
}
```
but now i think i found a bug on your snack as this right thumb can't slide on web

![image](https://user-images.githubusercontent.com/10884331/149702801-1f8ab795-dceb-41ad-bbb5-ccf6d02f2f0f.png)

cmiiw

**Comment by miblanchard** [comment]
Please open a separate issue for that so it’s easier to keep track. 

I’m going to close this one as you were able to resolve it.
