### ISSUE TITLE
inputRange exception if minimumValue is greater than maximumValue

### ISSUE THREAD

**Issue by rubewijk** [miblanchard/react-native-slider#330]
I recently ran into a bug in my app which in some scenarios caused it to set the `minimumValue` prop to be greater than the `maximumValue` prop. This in turn caused the slider to throw a `Invariant Violation: inputRange must be monotonically non-decreasing` exception. 

Perhaps it's not really an issue since the props are not supposed to be set like that, but I thought someone might find the information useful. Thanks for writing this great library! :)

**Comment by miblanchard** [comment]
Thanks for sharing. I'll try to look into providing a cleaner message/maybe adding logic to switch the values of the non is higher than max.

**Comment by miblanchard** [comment]
Closing for now.  Thanks for using the package.

**Comment by miblanchard** [comment]
Closing now.
