### ISSUE TITLE
Error: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by Moodax** [miblanchard/react-native-slider#331]
When trying to implement your component, I get this error:

 ./node_modules/@miblanchard/react-native-slider/lib/index.js 53:22
Module parse failed: Unexpected token (53:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     }
|     if (Array.isArray(values) && Array.isArray(newValues)) {
>         return values?.map((value, index) => {
|             let valueToSet = newValues[index];
|             if (value instanceof Animated.Value) {

I used the same implementation as shown in example.

**Comment by miblanchard** [comment]
Looks like your webpack config is not set up to handle optional chaining. You could add this dependency to the includes section of your webpack config.  That will likely resolve the issue.

**Comment by Moodax** [comment]
I think you're right, but I can't seem to find a tutorial on how to install webpack for React Native, and adding optional chaining plugin to Babel didn't make any difference. Can you please link me some easy to understand tutorial for webpack installation?
Thanks in advance!

**Comment by miblanchard** [comment]
@Moodax This babel config works for my use cases.

```    
return {
        plugins: ["@babel/plugin-proposal-export-namespace-from"],
        presets: [
            "module:metro-react-native-babel-preset",
            "@babel/preset-typescript",
        ],
    };
    
```

**Comment by miblanchard** [comment]
@Moodax I'm going to close this because it's not a problem with this library and can be resolved via babel.

**Comment by brucedk** [comment]
Same issue here... and babel config does not work

**Comment by brucedk** [comment]
@Moodax 
I managed to get working using this [example](https://github.com/ptomasroos/react-native-multi-slider/issues/205#issuecomment-723998147), just change the name of the package
