### ISSUE TITLE
It's not an issue, but I don't know how to update you about this short feature or collaborate, I am new to github.

### ISSUE THREAD

**Issue by VRDemon** [miblanchard/react-native-slider#333]
This patch adds only trackMarksClickable  which is needed by me in a project, maybe someone too need this type of feature:

[@miblanchard+react-native-slider+2.1.0.patch.txt](https://github.com/miblanchard/react-native-slider/files/8124406/%40miblanchard%2Breact-native-slider%2B2.1.0.patch.txt)

**Comment by miblanchard** [comment]
@VRDemon  can you open a pull request with this please?

**Comment by miblanchard** [comment]
@VRDemon can you explain the use case for this feature please?

**Comment by VRDemon** [comment]
@miblanchard This feature gives you option that only the track marks are going to be clicked,
In between slider values are ignored on slider momentum end.

**Comment by miblanchard** [comment]
Closing for now, feel free to open a PR with this change if interested.
