### ISSUE TITLE
Always grabbing left part of the slider, it can get stuck

### ISSUE THREAD

**Issue by christianrank** [miblanchard/react-native-slider#339]
If I have a range slider with both ends close to each other, it is always grabbing the left end of the silder.

So when I move both ends to the left, it is impossible to change it back, because the right end gets stuck behind the left end.

![slider_issue](https://user-images.githubusercontent.com/3001431/162977119-30e97dc4-cc0a-459d-9f43-a72ef4b03ba8.gif)

**Comment by dkulakov** [comment]
Hi @christianrank , did you find any workaround for that issue?

**Comment by christianrank** [comment]
Hi @dkulakov, unfortunately not, I didn't follow up on that issue and it still exists in our app.

**Comment by dkulakov** [comment]
@christianrank I'm going to switch to this [library](https://codesandbox.io/s/ydkl9?file=/src/RangeSlider/index.js)

**Comment by miblanchard** [comment]
Unclear how much this is impacting users, going to close for the time.

**Comment by janusqa** [comment]
I am also having this issue.  Unable to move the right thumb if it gets too close to the left thumb. Also the right thumb cannot be positioned over left thumb to get  a range of say 22-22, smallest range is 22-23 with step set to 1.
Can this be reopened?
