### ISSUE TITLE
renderAboveThumbComponent should return the value instead of index

### ISSUE THREAD

**Issue by sibasishm** [miblanchard/react-native-slider#340]
Currently the `renderAboveThumbComponent` prop takes a function that takes index as a parameter. I don't understand how that is useful.
Instead if it can return the current value that the thumb is at, it would be useful to render a tooltip above the slider.

**Comment by joseortiz9** [comment]
Hey, I made a PR with this feature, please check it out so the maintainer can merge it
[#347](https://github.com/miblanchard/react-native-slider/pull/347)

**Comment by miblanchard** [comment]
Merged #347, and made a slight tweak so the order of the function params remains the same as it was previously.
