### ISSUE TITLE
Feature: please export SliderProps

### ISSUE THREAD

**Issue by hirbod** [miblanchard/react-native-slider#343]
I want to type my component but I am not able to since SliderProps are not exported. The community slider package does export it though (I migrated to yours which was definitely the best decision)

<img width="979" alt="Bildschirmfoto 2022-04-25 um 10 17 19" src="https://user-images.githubusercontent.com/504909/165048706-b7f1a8cc-0188-4011-848d-c4755831ae38.png">

**Comment by hirbod** [comment]
This package does export the types which have been generated automatically
https://github.com/miblanchard/react-native-slider/blob/main/package.json#L6

Compared to the community package:
https://github.com/callstack/react-native-slider/blob/main/src/package.json#L12

**Comment by miblanchard** [comment]
@hirbod are you saying the types definition in my package.json is incorrect, or SliderProps needs an additional export beyond that?

**Comment by hirbod** [comment]
It's been a while, but irc the export was missing

**Comment by hirbod** [comment]
Oh yeah, just read the error message in the screenshot

**Comment by Jacknes** [comment]
Bump! Would also love this.

**Comment by konne88** [comment]
For the time being, you can work around this problem with:

```type SliderProps = Parameters<NonNullable<Slider['shouldComponentUpdate']>>[0];```

**Comment by jiwtir** [comment]
bump, it'll be of great value to the consumers of this package!

**Comment by emilfjellstrom** [comment]
`SliderProps` can now be imported as of version **2.3.0** `import { SliderProps } from '@miblanchard/react-native-slider/lib/types';`
