### ISSUE TITLE
testID props is not found(For Jest test case)

### ISSUE THREAD

**Issue by vishaldhanotiyadev** [miblanchard/react-native-slider#353]
Is there any way to write a test case for the slider? When I try to write test case but I am unable to find testID in the slider module.

**Comment by miblanchard** [comment]
@vishaldhanotiyapersistent you're right that there isn’t currently any way to set a testID. Looking at the render hierarchy there isn’t a great place to put one. Many testing tool should also allow you to find elements by another mechanism as well.

**Comment by vishaldhanotiyadev** [comment]
Yeah, I did the same set a testID to view and then check the children component render hierarchy to write the test case..

is there any plan in the near future to add testID in the slider?

**Comment by miblanchard** [comment]
Since there isn't a good element to attach the test Id I don't have any plans to support a testId prop anytime soon.

**Comment by shoffing** [comment]
Without this there's currently no way to set the slider's value in Jest tests.

With @testing-library/react-native, the only options for querying are:

- ByRole
- ByLabelText
- ByPlaceholderText
- ByDisplayValue
- ByText
- ByHintText
- ByTestId

None of which can be used to find this slider.

**Comment by shoffing** [comment]
Not a big deal though, just causes TS errors which need to be ignored:

```
          <Slider
            // @ts-ignore
            testID="player-count-slider"
```
