### ISSUE TITLE
renderBelowThumbComponent available in master but not yet published to npm

### ISSUE THREAD

**Issue by sruli** [miblanchard/react-native-slider#359]
Hey, 

I found this library today and I'm really excited about it. Great work, thank you. I really appreciate the ability to customize the styles to match our designs so that I don't need to write the component myself to get the styles we need.

I noticed a `renderBelowThumbComponent` prop in the master branch that has not yet been published to npm. That would be really helpful. Are there plans for a new release soon?

Thanks.

**Comment by tonyneel** [comment]
I also just noticed this issue.

**Comment by tonyneel** [comment]
> Hey,
> 
> I found this library today and I'm really excited about it. Great work, thank you. I really appreciate the ability to customize the styles to match our designs so that I don't need to write the component myself to get the styles we need.
> 
> I noticed a `renderBelowThumbComponent` prop in the master branch that has not yet been published to npm. That would be really helpful. Are there plans for a new release soon?
> 
> Thanks.

I figured out you can just add a top style attribute and it will do the same thing. I did top: '55px'

**Comment by miblanchard** [comment]
Thanks for the reminder!  Just published 2.2.0

**Comment by dlindsey-olioapps** [comment]
Hello @miblanchard !

I am having this issue as well. Just this morning I installed with `yarn add @miblanchard/react-native-slider` but the renderBelowThumbComponent doesn't seem to be present in the library (though it is listed in the node_module readme).

Thanks!

**Comment by ArjunPatidarRadix** [comment]
Hey, `renderBelowThumbComponent` is not available in 2.2.0, Please check

**Comment by Morpheus-W** [comment]
> Thanks for the reminder! Just published 2.2.0

not found,maybe It slipped your mind

**Comment by miblanchard** [comment]
Closing as this should not be on npm.
