### ISSUE TITLE
Slider types

### ISSUE THREAD

**Issue by nekiro** [miblanchard/react-native-slider#361]
Please export types such as:
- SliderProps
- SliderOnChangeCallback

I'm unable to use these types to define my own component basing on this one.

Edit:
Found out SliderProps is possible to import from
`@miblanchard/react-native-slider/lib/types`

SliderOnChangeCallback is not exported from anywhere though.

**Comment by rshettyawaken** [comment]
@nekiro I agree! I would like to extend my components prop with SldierProps too.
