### ISSUE TITLE
Missing types for minimumTrackStyle and maximumTrackStyle in latest release (2.2.0)

### ISSUE THREAD

**Issue by ockam** [miblanchard/react-native-slider#382]
The title says it all: release 2.2.0 doesn’t includes types for `minimumTrackStyle` and `maximumTrackStyle`

I tried to build the `main` branch locally and the types are present. 

I guess there was an issue with the publishing process.

**Comment by Samipya** [comment]
+1, experiencing the same issue. @miblanchard - can you please check this? It would be really helpful for us

**Comment by milik27** [comment]
+1

**Comment by miblanchard** [comment]
@ockam @Samipya - can you check 2.3.1 please?

**Comment by ockam** [comment]
@miblanchard Works! Thanks!
