### ISSUE TITLE
Restrict to "go back"

### ISSUE THREAD

**Issue by dlogvin** [miblanchard/react-native-slider#57]
Is there a way to not let the user bring the slider back? for example, set it on 30 from 100, and not let the user go behind 30.

**Comment by miblanchard** [comment]
@dlogvin would your use case support setting 30 as the minValue?  That would change the left side starting point and a user could not see the value to anything below that.

**Comment by dlogvin** [comment]
My code currently looks like this:

```
                                        <Slider
                                            minValue={this.state.progressValue}
                                            step={0.1}
                                            onValueChange={progressValue => this.setState({ progressValue })}
                                        />
```

But it acts strange: 

[This is what happens](https://gyazo.com/1aac2a08ae652bf58eb8af073d67f74c)

**Comment by miblanchard** [comment]
@dlogvin  from the code sample you shared

```
<Slider 
  minValue={this.state.progressValue}
  step={0.1}
  onValueChange={progressValue => this.setState({ progressValue })}
/>
```

You don't want to update the minValue based on the slider state. The min should stay the same always, so if you want to make sure a user can't go below 30 you could set minValue to 30, and leave it at 30.

**Comment by miblanchard** [comment]
@dlogvin Did this resolve your issue?
