### ISSUE TITLE
Does not work as expected when RTL true

### ISSUE THREAD

**Issue by Hivenon** [miblanchard/react-native-slider#58]
There is a problem when RTL is true.

Code :
`<_Slider
      value={0.5}
      minimumValue={0}
      maximumValue={1}
      minimumTrackTintColor="red"
      maximumTrackTintColor="blue"
    />`

Output : 
[https://i.ibb.co/yqsm8PC/output.png](https://i.ibb.co/yqsm8PC/output.png)

Expected: 
[https://i.ibb.co/s5xTgmH/expected.png](https://i.ibb.co/s5xTgmH/expected.png)
or:
[https://i.ibb.co/w42GsJg/or-expected.png](https://i.ibb.co/w42GsJg/or-expected.png)

**Comment by miblanchard** [comment]
@Hivenon RTL support is not something I have a need for at the moment, but I would certainly welcome any PR that fixes the problem you found.

**Comment by Hivenon** [comment]
I fixed problem and sended pr from @Venon-IT. Take a look

**Comment by miblanchard** [comment]
Fixed in #73

**Comment by miblanchard** [comment]
Closed by #74
