### ISSUE TITLE
Array value for thumbStyle is no longer working

### ISSUE THREAD

**Issue by rkbhochalya** [miblanchard/react-native-slider#77]
For some reason, this no longer works in the current version:

```js
<Slider
  thumbStyle={[styles.thumb, thumbStyles]}
/>
```

**Comment by miblanchard** [comment]
@rkbhochalya I'll take a look soon, but in the mean one can you merge the styles before you pass it on to the component and see if they unblocks you for now?

**Comment by rkbhochalya** [comment]
@miblanchard yes thats what I did and it worked. Thanks!

**Comment by miblanchard** [comment]
@rkbhochalya - After looking back at the code again we only intend to support a single style object as the incoming prop type, and not an array of styles.  Sorry for the change that required.  The flow and TS types have been consistent on this as far as I can see.  Thank you for using the library, and we welcome any suggestions/enhancement PRs 😄

**Comment by dario30186** [comment]
Hi,
I'm trying to apply a style to thumb with property thumbStyle:
`        <Slider
         ...
          thumbStyle={styles.thumb}
        />`

and my thumb class:
`  thumb: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },`

but the style is not applied. 
@miblanchard do you have any suggestions ?

**Comment by dario30186** [comment]
If I apply the style like this then it works:
`thumbStyle={{ borderRadius: 5, height: 10, width: 10 }}`
